server:
  servlet:
    session:
      cookie:
        path: ${tafeladmin.server.relativeBaseUrl}
  tomcat:
    accesslog:
      enabled: true
      directory: logs

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db-migration
    group: true
    ignoreMissingMigrations: true

security:
  jwtToken:
    secret:
      algorithm: HmacSHA512
    expirationTimeInSeconds: 36000 # 10 hours

tafeladmin:
  server:
    relativeBaseUrl: /
