create table if not exists static_countries
(
    id   bigint generated by default as identity (start with 1) primary key,
    code varchar(2)  not null,
    name varchar(50) not null
);
create unique index if not exists uix_code on static_countries (code);

-- country data
INSERT INTO static_countries(name, code)
VALUES ('Afghanistan', 'AF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ägypten', 'EG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Aland', 'AX')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Albanien', 'AL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Algerien', 'DZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Andorra', 'AD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Angola', 'AO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Anguilla', 'AI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Antarktis', 'AQ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Antigua und Barbuda', 'AG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Äquatorial Guinea', 'GQ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Argentinien', 'AR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Armenien', 'AM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Aruba', 'AW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Aserbeidschan', 'AZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Äthiopien', 'ET')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Australien', 'AU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bahamas', 'BS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bahrain', 'BH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bangladesch', 'BD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Barbados', 'BB')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Belarus (Weissrussland)', 'BY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Belgien', 'BE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Belize', 'BZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Benin', 'BJ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bermuda', 'BM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bhutan', 'BT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bolivien', 'BO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bonaire, St. Eustatius und Saba', 'BQ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bosnien und Herzegowina', 'BA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Botsuana', 'BW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bouvetinsel', 'BV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Brasilien', 'BR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Brit.Terr.Im Indischen Ozean', 'IO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Brunei Darussalam', 'BN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Bulgarien', 'BG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Burkina Faso', 'BF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Burundi', 'BI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Chile', 'CL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('China', 'CN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Cook-Inseln Neuseel.Verwaltung', 'CK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Costa Rica', 'CR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Cote D''Ivoire (Elfenbeinkueste)', 'CI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Curaçao', 'CW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Dänemark', 'DK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Deutschland', 'DE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Dominica', 'DM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Dominikanische Republik', 'DO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Dschibuti', 'DJ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ecuador', 'EC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('El Salvador', 'SV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Eritrea', 'ER')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Estland', 'EE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Eswatini', 'SZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Faeroeer Inseln Dän.Verwaltung', 'FO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Falklandinseln (Malvinen)', 'FK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Fidschi', 'FJ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Finnland', 'FI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Frankreich', 'FR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Franz. Südgebiete', 'TF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Französisch Guayana', 'GF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Französisch Polynesien', 'PF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Gabun', 'GA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Gambia', 'GM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Georgien', 'GE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ghana', 'GH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Gibraltar', 'GI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Grenada', 'GD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Griechenland', 'GR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Grönland (Dän.Verwaltung)', 'GL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Großbritannien', 'GB')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guadeloupe (Franz.Verwaltung)', 'GP')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guam (US-Verwaltung)', 'GU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guatemala', 'GT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guernsey Insel', 'GG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guinea', 'GN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guinea-Bissau', 'GW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Guyana', 'GY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Haiti', 'HT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Heard und Mc Donald Inseln (unter Austr.Verw.)', 'HM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Honduras', 'HN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Hongkong', 'HK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Indien', 'IN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Indonesien', 'ID')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Irak', 'IQ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Iran', 'IR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Irland', 'IE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Island', 'IS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Israel', 'IL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Italien', 'IT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jamaika', 'JM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Japan', 'JP')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jemen', 'YE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jersey Insel', 'JE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jordanien', 'JO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jungfern-Inseln (Britisch)', 'VG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Jungfern-Inseln (USA)', 'VI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kaimaninseln', 'KY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kambodscha', 'KH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kamerun', 'CM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kanada', 'CA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kap Verde', 'CV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kasachstan', 'KZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Katar', 'QA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kenia', 'KE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kirgisistan', 'KG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kiribati', 'KI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kokosinseln (Keeling)', 'CC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kolumbien', 'CO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Komoren', 'KM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kongo', 'CG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kongo, Demokratische Republik', 'CD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Korea, Demokratische Volksrepublik', 'KP')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Korea, Republik', 'KR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kosovo', 'XK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kroatien', 'HR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kuba', 'CU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Kuwait', 'KW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Laos', 'LA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Lesotho', 'LS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Lettland', 'LV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Libanon', 'LB')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Liberien', 'LR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Libysch-Arabische Dschamahirija', 'LY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Liechtenstein', 'LI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Litauen', 'LT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Luxemburg', 'LU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Macao', 'MO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Madagaskar', 'MG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Malawi', 'MW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Malaysia', 'MY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Malediven', 'MV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mali', 'ML')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Malta', 'MT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Man, Insel', 'IM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Marianen, Nördliche', 'MP')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Marokko', 'MA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Marshall Inseln', 'MH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Martinique Franz.Verwaltung', 'MQ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mauretanien', 'MR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mauritius', 'MU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mayotte', 'YT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mexiko', 'MX')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mikronesien', 'FM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Moldau, Republik', 'MD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Monaco', 'MC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mongolei', 'MN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Montenegro', 'ME')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Montserrat (GB-Verwaltung)', 'MS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Mosambik', 'MZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Myanmar', 'MM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Namibia', 'NA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Nauru', 'NR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Nepal', 'NP')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Neukaledonien', 'NC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Neuseeland', 'NZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Nicaragua', 'NI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Niederlande', 'NL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Niger', 'NE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Nigeria', 'NG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Niue (Neuseel.Verwaltung)', 'NU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Norfolkinsel', 'NF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Norwegen', 'NO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Oman', 'OM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Österreich', 'AT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Pakistan', 'PK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Palästina', 'PS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Palau', 'PW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Panama', 'PA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Papua Neuguinea', 'PG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Paraguay', 'PY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Peru', 'PE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Philippinen', 'PH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Pitcairninsel', 'PN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Polen', 'PL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Portugal', 'PT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Puerto Rico (US-Verwaltung)', 'PR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Republik Nordmazedonien', 'MK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Reunion', 'RE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ruanda', 'RW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Rumänien', 'RO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Russische Föderation', 'RU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Saint Barthélemy (Franz.Verwaltung)', 'BL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Saint Martin (Franz. Verwaltung)', 'MF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Salomonen', 'SB')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Sambia', 'ZM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Samoa-Amerikanisch (US-Verwaltung)', 'AS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Samoa-West', 'WS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('San Marino', 'SM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Sao Tome und Principe', 'ST')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Saudi-Arabien', 'SA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Schweden', 'SE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Schweiz', 'CH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Senegal', 'SN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Serbien (exkl. Kosovo)', 'RS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Seychellen', 'SC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Sierra Leone', 'SL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Simbabwe', 'ZW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Singapur', 'SG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Slowakei', 'SK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Slowenien', 'SI')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Somalia', 'SO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Spanien', 'ES')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Spitzb. und Jan Mayen Insel (Norw.Verw.)', 'SJ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Sri Lanka', 'LK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St. Martin', 'SX')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St. Vincent und die Grenadinen', 'VC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St.Helena', 'SH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St.Kitts und Nevis', 'KN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St.Lucia', 'LC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('St.Pierre und Miquelon', 'PM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Südafrika', 'ZA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Sudan', 'SD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Südgeorgien und Süd-Sandwich-Insel', 'GS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Südsudan', 'SS')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Suriname', 'SR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Syrien', 'SY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tadschikistan', 'TJ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Taiwan', 'TW')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tansania, Vereinigte Republik', 'TZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Thailand', 'TH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Timor-Leste', 'TL')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Togo', 'TG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tokelau (Neuseel.Verwaltung)', 'TK')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tonga', 'TO')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Trinidad und Tobago', 'TT')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tschad', 'TD')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tschechien', 'CZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tunesien', 'TN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Türkei', 'TR')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Turkmenistan', 'TM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Turks- und Caicosinseln', 'TC')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Tuvalu', 'TV')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Uganda', 'UG')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ukraine', 'UA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Ungarn', 'HU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Uruguay', 'UY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('USA - Sonstige Kleine Inseln', 'UM')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('USA - Vereinigte Staaten', 'US')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Usbekistan', 'UZ')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Vanuatu', 'VU')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Vatikan', 'VA')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Venezuela', 'VE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Vereinigte Arabische Emirate', 'AE')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Vietnam', 'VN')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Wallis und Futuna', 'WF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Weihnachtsinsel (Austr.Verwaltung)', 'CX')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Westsahara Eigenst.Staat', 'EH')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Zentralafrikanische Republik', 'CF')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Zypern', 'CY')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
INSERT INTO static_countries(name, code)
VALUES ('Staatenlos', 'S0')
ON CONFLICT (code) DO UPDATE
    SET name = excluded.name,
        code = excluded.code;
