DROP TABLE IF EXISTS static_countries;

create table static_countries
(
    id   bigint generated by default as identity (start with 1) primary key,
    code varchar(2)  not null,
    name varchar(50) not null
);

create unique index uix_code on static_countries (code);

-- country data
INSERT INTO static_countries(name, code)
VALUES ('Afghanistan', 'AF');
INSERT INTO static_countries(name, code)
VALUES ('Ägypten', 'EG');
INSERT INTO static_countries(name, code)
VALUES ('Aland', 'AX');
INSERT INTO static_countries(name, code)
VALUES ('Albanien', 'AL');
INSERT INTO static_countries(name, code)
VALUES ('Algerien', 'DZ');
INSERT INTO static_countries(name, code)
VALUES ('Andorra', 'AD');
INSERT INTO static_countries(name, code)
VALUES ('Angola', 'AO');
INSERT INTO static_countries(name, code)
VALUES ('Anguilla', 'AI');
INSERT INTO static_countries(name, code)
VALUES ('Antarktis', 'AQ');
INSERT INTO static_countries(name, code)
VALUES ('Antigua und Barbuda', 'AG');
INSERT INTO static_countries(name, code)
VALUES ('Äquatorial Guinea', 'GQ');
INSERT INTO static_countries(name, code)
VALUES ('Argentinien', 'AR');
INSERT INTO static_countries(name, code)
VALUES ('Armenien', 'AM');
INSERT INTO static_countries(name, code)
VALUES ('Aruba', 'AW');
INSERT INTO static_countries(name, code)
VALUES ('Aserbeidschan', 'AZ');
INSERT INTO static_countries(name, code)
VALUES ('Äthiopien', 'ET');
INSERT INTO static_countries(name, code)
VALUES ('Australien', 'AU');
INSERT INTO static_countries(name, code)
VALUES ('Bahamas', 'BS');
INSERT INTO static_countries(name, code)
VALUES ('Bahrain', 'BH');
INSERT INTO static_countries(name, code)
VALUES ('Bangladesch', 'BD');
INSERT INTO static_countries(name, code)
VALUES ('Barbados', 'BB');
INSERT INTO static_countries(name, code)
VALUES ('Belarus (Weissrussland)', 'BY');
INSERT INTO static_countries(name, code)
VALUES ('Belgien', 'BE');
INSERT INTO static_countries(name, code)
VALUES ('Belize', 'BZ');
INSERT INTO static_countries(name, code)
VALUES ('Benin', 'BJ');
INSERT INTO static_countries(name, code)
VALUES ('Bermuda', 'BM');
INSERT INTO static_countries(name, code)
VALUES ('Bhutan', 'BT');
INSERT INTO static_countries(name, code)
VALUES ('Bolivien', 'BO');
INSERT INTO static_countries(name, code)
VALUES ('Bonaire, St. Eustatius und Saba', 'BQ');
INSERT INTO static_countries(name, code)
VALUES ('Bosnien und Herzegowina', 'BA');
INSERT INTO static_countries(name, code)
VALUES ('Botsuana', 'BW');
INSERT INTO static_countries(name, code)
VALUES ('Bouvetinsel', 'BV');
INSERT INTO static_countries(name, code)
VALUES ('Brasilien', 'BR');
INSERT INTO static_countries(name, code)
VALUES ('Brit.Terr.Im Indischen Ozean', 'IO');
INSERT INTO static_countries(name, code)
VALUES ('Brunei Darussalam', 'BN');
INSERT INTO static_countries(name, code)
VALUES ('Bulgarien', 'BG');
INSERT INTO static_countries(name, code)
VALUES ('Burkina Faso', 'BF');
INSERT INTO static_countries(name, code)
VALUES ('Burundi', 'BI');
INSERT INTO static_countries(name, code)
VALUES ('Chile', 'CL');
INSERT INTO static_countries(name, code)
VALUES ('China', 'CN');
INSERT INTO static_countries(name, code)
VALUES ('Cook-Inseln Neuseel.Verwaltung', 'CK');
INSERT INTO static_countries(name, code)
VALUES ('Costa Rica', 'CR');
INSERT INTO static_countries(name, code)
VALUES ('Cote D''Ivoire (Elfenbeinkueste)', 'CI');
INSERT INTO static_countries(name, code)
VALUES ('Curaçao', 'CW');
INSERT INTO static_countries(name, code)
VALUES ('Dänemark', 'DK');
INSERT INTO static_countries(name, code)
VALUES ('Deutschland', 'DE');
INSERT INTO static_countries(name, code)
VALUES ('Dominica', 'DM');
INSERT INTO static_countries(name, code)
VALUES ('Dominikanische Republik', 'DO');
INSERT INTO static_countries(name, code)
VALUES ('Dschibuti', 'DJ');
INSERT INTO static_countries(name, code)
VALUES ('Ecuador', 'EC');
INSERT INTO static_countries(name, code)
VALUES ('El Salvador', 'SV');
INSERT INTO static_countries(name, code)
VALUES ('Eritrea', 'ER');
INSERT INTO static_countries(name, code)
VALUES ('Estland', 'EE');
INSERT INTO static_countries(name, code)
VALUES ('Eswatini', 'SZ');
INSERT INTO static_countries(name, code)
VALUES ('Faeroeer Inseln Dän.Verwaltung', 'FO');
INSERT INTO static_countries(name, code)
VALUES ('Falklandinseln (Malvinen)', 'FK');
INSERT INTO static_countries(name, code)
VALUES ('Fidschi', 'FJ');
INSERT INTO static_countries(name, code)
VALUES ('Finnland', 'FI');
INSERT INTO static_countries(name, code)
VALUES ('Frankreich', 'FR');
INSERT INTO static_countries(name, code)
VALUES ('Franz. Südgebiete', 'TF');
INSERT INTO static_countries(name, code)
VALUES ('Französisch Guayana', 'GF');
INSERT INTO static_countries(name, code)
VALUES ('Französisch Polynesien', 'PF');
INSERT INTO static_countries(name, code)
VALUES ('Gabun', 'GA');
INSERT INTO static_countries(name, code)
VALUES ('Gambia', 'GM');
INSERT INTO static_countries(name, code)
VALUES ('Georgien', 'GE');
INSERT INTO static_countries(name, code)
VALUES ('Ghana', 'GH');
INSERT INTO static_countries(name, code)
VALUES ('Gibraltar', 'GI');
INSERT INTO static_countries(name, code)
VALUES ('Grenada', 'GD');
INSERT INTO static_countries(name, code)
VALUES ('Griechenland', 'GR');
INSERT INTO static_countries(name, code)
VALUES ('Grönland (Dän.Verwaltung)', 'GL');
INSERT INTO static_countries(name, code)
VALUES ('Großbritannien', 'GB');
INSERT INTO static_countries(name, code)
VALUES ('Guadeloupe (Franz.Verwaltung)', 'GP');
INSERT INTO static_countries(name, code)
VALUES ('Guam (US-Verwaltung)', 'GU');
INSERT INTO static_countries(name, code)
VALUES ('Guatemala', 'GT');
INSERT INTO static_countries(name, code)
VALUES ('Guernsey Insel', 'GG');
INSERT INTO static_countries(name, code)
VALUES ('Guinea', 'GN');
INSERT INTO static_countries(name, code)
VALUES ('Guinea-Bissau', 'GW');
INSERT INTO static_countries(name, code)
VALUES ('Guyana', 'GY');
INSERT INTO static_countries(name, code)
VALUES ('Haiti', 'HT');
INSERT INTO static_countries(name, code)
VALUES ('Heard und Mc Donald Inseln (unter Austr.Verw.)', 'HM');
INSERT INTO static_countries(name, code)
VALUES ('Honduras', 'HN');
INSERT INTO static_countries(name, code)
VALUES ('Hongkong', 'HK');
INSERT INTO static_countries(name, code)
VALUES ('Indien', 'IN');
INSERT INTO static_countries(name, code)
VALUES ('Indonesien', 'ID');
INSERT INTO static_countries(name, code)
VALUES ('Irak', 'IQ');
INSERT INTO static_countries(name, code)
VALUES ('Iran', 'IR');
INSERT INTO static_countries(name, code)
VALUES ('Irland', 'IE');
INSERT INTO static_countries(name, code)
VALUES ('Island', 'IS');
INSERT INTO static_countries(name, code)
VALUES ('Israel', 'IL');
INSERT INTO static_countries(name, code)
VALUES ('Italien', 'IT');
INSERT INTO static_countries(name, code)
VALUES ('Jamaika', 'JM');
INSERT INTO static_countries(name, code)
VALUES ('Japan', 'JP');
INSERT INTO static_countries(name, code)
VALUES ('Jemen', 'YE');
INSERT INTO static_countries(name, code)
VALUES ('Jersey Insel', 'JE');
INSERT INTO static_countries(name, code)
VALUES ('Jordanien', 'JO');
INSERT INTO static_countries(name, code)
VALUES ('Jungfern-Inseln (Britisch)', 'VG');
INSERT INTO static_countries(name, code)
VALUES ('Jungfern-Inseln (USA)', 'VI');
INSERT INTO static_countries(name, code)
VALUES ('Kaimaninseln', 'KY');
INSERT INTO static_countries(name, code)
VALUES ('Kambodscha', 'KH');
INSERT INTO static_countries(name, code)
VALUES ('Kamerun', 'CM');
INSERT INTO static_countries(name, code)
VALUES ('Kanada', 'CA');
INSERT INTO static_countries(name, code)
VALUES ('Kap Verde', 'CV');
INSERT INTO static_countries(name, code)
VALUES ('Kasachstan', 'KZ');
INSERT INTO static_countries(name, code)
VALUES ('Katar', 'QA');
INSERT INTO static_countries(name, code)
VALUES ('Kenia', 'KE');
INSERT INTO static_countries(name, code)
VALUES ('Kirgisistan', 'KG');
INSERT INTO static_countries(name, code)
VALUES ('Kiribati', 'KI');
INSERT INTO static_countries(name, code)
VALUES ('Kokosinseln (Keeling)', 'CC');
INSERT INTO static_countries(name, code)
VALUES ('Kolumbien', 'CO');
INSERT INTO static_countries(name, code)
VALUES ('Komoren', 'KM');
INSERT INTO static_countries(name, code)
VALUES ('Kongo', 'CG');
INSERT INTO static_countries(name, code)
VALUES ('Kongo, Demokratische Republik', 'CD');
INSERT INTO static_countries(name, code)
VALUES ('Korea, Demokratische Volksrepublik', 'KP');
INSERT INTO static_countries(name, code)
VALUES ('Korea, Republik', 'KR');
INSERT INTO static_countries(name, code)
VALUES ('Kosovo', 'XK');
INSERT INTO static_countries(name, code)
VALUES ('Kroatien', 'HR');
INSERT INTO static_countries(name, code)
VALUES ('Kuba', 'CU');
INSERT INTO static_countries(name, code)
VALUES ('Kuwait', 'KW');
INSERT INTO static_countries(name, code)
VALUES ('Laos', 'LA');
INSERT INTO static_countries(name, code)
VALUES ('Lesotho', 'LS');
INSERT INTO static_countries(name, code)
VALUES ('Lettland', 'LV');
INSERT INTO static_countries(name, code)
VALUES ('Libanon', 'LB');
INSERT INTO static_countries(name, code)
VALUES ('Liberien', 'LR');
INSERT INTO static_countries(name, code)
VALUES ('Libysch-Arabische Dschamahirija', 'LY');
INSERT INTO static_countries(name, code)
VALUES ('Liechtenstein', 'LI');
INSERT INTO static_countries(name, code)
VALUES ('Litauen', 'LT');
INSERT INTO static_countries(name, code)
VALUES ('Luxemburg', 'LU');
INSERT INTO static_countries(name, code)
VALUES ('Macao', 'MO');
INSERT INTO static_countries(name, code)
VALUES ('Madagaskar', 'MG');
INSERT INTO static_countries(name, code)
VALUES ('Malawi', 'MW');
INSERT INTO static_countries(name, code)
VALUES ('Malaysia', 'MY');
INSERT INTO static_countries(name, code)
VALUES ('Malediven', 'MV');
INSERT INTO static_countries(name, code)
VALUES ('Mali', 'ML');
INSERT INTO static_countries(name, code)
VALUES ('Malta', 'MT');
INSERT INTO static_countries(name, code)
VALUES ('Man, Insel', 'IM');
INSERT INTO static_countries(name, code)
VALUES ('Marianen, Nördliche', 'MP');
INSERT INTO static_countries(name, code)
VALUES ('Marokko', 'MA');
INSERT INTO static_countries(name, code)
VALUES ('Marshall Inseln', 'MH');
INSERT INTO static_countries(name, code)
VALUES ('Martinique Franz.Verwaltung', 'MQ');
INSERT INTO static_countries(name, code)
VALUES ('Mauretanien', 'MR');
INSERT INTO static_countries(name, code)
VALUES ('Mauritius', 'MU');
INSERT INTO static_countries(name, code)
VALUES ('Mayotte', 'YT');
INSERT INTO static_countries(name, code)
VALUES ('Mexiko', 'MX');
INSERT INTO static_countries(name, code)
VALUES ('Mikronesien', 'FM');
INSERT INTO static_countries(name, code)
VALUES ('Moldau, Republik', 'MD');
INSERT INTO static_countries(name, code)
VALUES ('Monaco', 'MC');
INSERT INTO static_countries(name, code)
VALUES ('Mongolei', 'MN');
INSERT INTO static_countries(name, code)
VALUES ('Montenegro', 'ME');
INSERT INTO static_countries(name, code)
VALUES ('Montserrat (GB-Verwaltung)', 'MS');
INSERT INTO static_countries(name, code)
VALUES ('Mosambik', 'MZ');
INSERT INTO static_countries(name, code)
VALUES ('Myanmar', 'MM');
INSERT INTO static_countries(name, code)
VALUES ('Namibia', 'NA');
INSERT INTO static_countries(name, code)
VALUES ('Nauru', 'NR');
INSERT INTO static_countries(name, code)
VALUES ('Nepal', 'NP');
INSERT INTO static_countries(name, code)
VALUES ('Neukaledonien', 'NC');
INSERT INTO static_countries(name, code)
VALUES ('Neuseeland', 'NZ');
INSERT INTO static_countries(name, code)
VALUES ('Nicaragua', 'NI');
INSERT INTO static_countries(name, code)
VALUES ('Niederlande', 'NL');
INSERT INTO static_countries(name, code)
VALUES ('Niger', 'NE');
INSERT INTO static_countries(name, code)
VALUES ('Nigeria', 'NG');
INSERT INTO static_countries(name, code)
VALUES ('Niue (Neuseel.Verwaltung)', 'NU');
INSERT INTO static_countries(name, code)
VALUES ('Norfolkinsel', 'NF');
INSERT INTO static_countries(name, code)
VALUES ('Norwegen', 'NO');
INSERT INTO static_countries(name, code)
VALUES ('Oman', 'OM');
INSERT INTO static_countries(name, code)
VALUES ('Österreich', 'AT');
INSERT INTO static_countries(name, code)
VALUES ('Pakistan', 'PK');
INSERT INTO static_countries(name, code)
VALUES ('Palästina', 'PS');
INSERT INTO static_countries(name, code)
VALUES ('Palau', 'PW');
INSERT INTO static_countries(name, code)
VALUES ('Panama', 'PA');
INSERT INTO static_countries(name, code)
VALUES ('Papua Neuguinea', 'PG');
INSERT INTO static_countries(name, code)
VALUES ('Paraguay', 'PY');
INSERT INTO static_countries(name, code)
VALUES ('Peru', 'PE');
INSERT INTO static_countries(name, code)
VALUES ('Philippinen', 'PH');
INSERT INTO static_countries(name, code)
VALUES ('Pitcairninsel', 'PN');
INSERT INTO static_countries(name, code)
VALUES ('Polen', 'PL');
INSERT INTO static_countries(name, code)
VALUES ('Portugal', 'PT');
INSERT INTO static_countries(name, code)
VALUES ('Puerto Rico (US-Verwaltung)', 'PR');
INSERT INTO static_countries(name, code)
VALUES ('Republik Nordmazedonien', 'MK');
INSERT INTO static_countries(name, code)
VALUES ('Reunion', 'RE');
INSERT INTO static_countries(name, code)
VALUES ('Ruanda', 'RW');
INSERT INTO static_countries(name, code)
VALUES ('Rumänien', 'RO');
INSERT INTO static_countries(name, code)
VALUES ('Russische Föderation', 'RU');
INSERT INTO static_countries(name, code)
VALUES ('Saint Barthélemy (Franz.Verwaltung)', 'BL');
INSERT INTO static_countries(name, code)
VALUES ('Saint Martin (Franz. Verwaltung)', 'MF');
INSERT INTO static_countries(name, code)
VALUES ('Salomonen', 'SB');
INSERT INTO static_countries(name, code)
VALUES ('Sambia', 'ZM');
INSERT INTO static_countries(name, code)
VALUES ('Samoa-Amerikanisch (US-Verwaltung)', 'AS');
INSERT INTO static_countries(name, code)
VALUES ('Samoa-West', 'WS');
INSERT INTO static_countries(name, code)
VALUES ('San Marino', 'SM');
INSERT INTO static_countries(name, code)
VALUES ('Sao Tome und Principe', 'ST');
INSERT INTO static_countries(name, code)
VALUES ('Saudi-Arabien', 'SA');
INSERT INTO static_countries(name, code)
VALUES ('Schweden', 'SE');
INSERT INTO static_countries(name, code)
VALUES ('Schweiz', 'CH');
INSERT INTO static_countries(name, code)
VALUES ('Senegal', 'SN');
INSERT INTO static_countries(name, code)
VALUES ('Serbien (exkl. Kosovo)', 'RS');
INSERT INTO static_countries(name, code)
VALUES ('Seychellen', 'SC');
INSERT INTO static_countries(name, code)
VALUES ('Sierra Leone', 'SL');
INSERT INTO static_countries(name, code)
VALUES ('Simbabwe', 'ZW');
INSERT INTO static_countries(name, code)
VALUES ('Singapur', 'SG');
INSERT INTO static_countries(name, code)
VALUES ('Slowakei', 'SK');
INSERT INTO static_countries(name, code)
VALUES ('Slowenien', 'SI');
INSERT INTO static_countries(name, code)
VALUES ('Somalia', 'SO');
INSERT INTO static_countries(name, code)
VALUES ('Spanien', 'ES');
INSERT INTO static_countries(name, code)
VALUES ('Spitzb. und Jan Mayen Insel (Norw.Verw.)', 'SJ');
INSERT INTO static_countries(name, code)
VALUES ('Sri Lanka', 'LK');
INSERT INTO static_countries(name, code)
VALUES ('St. Martin', 'SX');
INSERT INTO static_countries(name, code)
VALUES ('St. Vincent und die Grenadinen', 'VC');
INSERT INTO static_countries(name, code)
VALUES ('St.Helena', 'SH');
INSERT INTO static_countries(name, code)
VALUES ('St.Kitts und Nevis', 'KN');
INSERT INTO static_countries(name, code)
VALUES ('St.Lucia', 'LC');
INSERT INTO static_countries(name, code)
VALUES ('St.Pierre und Miquelon', 'PM');
INSERT INTO static_countries(name, code)
VALUES ('Südafrika', 'ZA');
INSERT INTO static_countries(name, code)
VALUES ('Sudan', 'SD');
INSERT INTO static_countries(name, code)
VALUES ('Südgeorgien und Süd-Sandwich-Insel', 'GS');
INSERT INTO static_countries(name, code)
VALUES ('Südsudan', 'SS');
INSERT INTO static_countries(name, code)
VALUES ('Suriname', 'SR');
INSERT INTO static_countries(name, code)
VALUES ('Syrien', 'SY');
INSERT INTO static_countries(name, code)
VALUES ('Tadschikistan', 'TJ');
INSERT INTO static_countries(name, code)
VALUES ('Taiwan', 'TW');
INSERT INTO static_countries(name, code)
VALUES ('Tansania, Vereinigte Republik', 'TZ');
INSERT INTO static_countries(name, code)
VALUES ('Thailand', 'TH');
INSERT INTO static_countries(name, code)
VALUES ('Timor-Leste', 'TL');
INSERT INTO static_countries(name, code)
VALUES ('Togo', 'TG');
INSERT INTO static_countries(name, code)
VALUES ('Tokelau (Neuseel.Verwaltung)', 'TK');
INSERT INTO static_countries(name, code)
VALUES ('Tonga', 'TO');
INSERT INTO static_countries(name, code)
VALUES ('Trinidad und Tobago', 'TT');
INSERT INTO static_countries(name, code)
VALUES ('Tschad', 'TD');
INSERT INTO static_countries(name, code)
VALUES ('Tschechien', 'CZ');
INSERT INTO static_countries(name, code)
VALUES ('Tunesien', 'TN');
INSERT INTO static_countries(name, code)
VALUES ('Türkei', 'TR');
INSERT INTO static_countries(name, code)
VALUES ('Turkmenistan', 'TM');
INSERT INTO static_countries(name, code)
VALUES ('Turks- und Caicosinseln', 'TC');
INSERT INTO static_countries(name, code)
VALUES ('Tuvalu', 'TV');
INSERT INTO static_countries(name, code)
VALUES ('Uganda', 'UG');
INSERT INTO static_countries(name, code)
VALUES ('Ukraine', 'UA');
INSERT INTO static_countries(name, code)
VALUES ('Ungarn', 'HU');
INSERT INTO static_countries(name, code)
VALUES ('Uruguay', 'UY');
INSERT INTO static_countries(name, code)
VALUES ('USA - Sonstige Kleine Inseln', 'UM');
INSERT INTO static_countries(name, code)
VALUES ('USA - Vereinigte Staaten', 'US');
INSERT INTO static_countries(name, code)
VALUES ('Usbekistan', 'UZ');
INSERT INTO static_countries(name, code)
VALUES ('Vanuatu', 'VU');
INSERT INTO static_countries(name, code)
VALUES ('Vatikan', 'VA');
INSERT INTO static_countries(name, code)
VALUES ('Venezuela', 'VE');
INSERT INTO static_countries(name, code)
VALUES ('Vereinigte Arabische Emirate', 'AE');
INSERT INTO static_countries(name, code)
VALUES ('Vietnam', 'VN');
INSERT INTO static_countries(name, code)
VALUES ('Wallis und Futuna', 'WF');
INSERT INTO static_countries(name, code)
VALUES ('Weihnachtsinsel (Austr.Verwaltung)', 'CX');
INSERT INTO static_countries(name, code)
VALUES ('Westsahara Eigenst.Staat', 'EH');
INSERT INTO static_countries(name, code)
VALUES ('Zentralafrikanische Republik', 'CF');
INSERT INTO static_countries(name, code)
VALUES ('Zypern', 'CY');
