### Get employees
GET {{baseApiPath}}/employees

### Find employees by searchInput (personnelNumber)
GET {{baseApiPath}}/employees?searchInput=00000

### Find employees by searchInput (firstname)
GET {{baseApiPath}}/employees?searchInput=scan

### Find employees by searchInput (lastname)
GET {{baseApiPath}}/employees?searchInput=User

### Save new employee
POST {{baseApiPath}}/employees
Content-Type: application/json

{
  "personnelNumber": "12345",
  "firstname": "first",
  "lastname": "last"
}
