### Get employees
GET {{baseApiPath}}/employees

### Get employee by personnelNumber
GET {{baseApiPath}}/employees?personnelNumber=00000

### Save new employee
POST {{baseApiPath}}/employees
Content-Type: application/json

{
  "personnelNumber": "12345",
  "firstname": "first",
  "lastname": "last"
}
