### Login
POST {{baseApiPath}}/login
Authorization: Basic {{encodedCredentials}}

> {%
    client.global.set("jwt", response.body["token"]);
%}

### Login fails - user not found
POST {{baseApiPath}}/login
Authorization: Basic d3Jvbmc6d3Jvbmc=

### Login fails - wrong password
POST {{baseApiPath}}/login
Authorization: Basic YWRtaW46d3Jvbmc=

### Change password
POST {{baseApiPath}}/users/change-password
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "passwordCurrent": "12345",
  "passwordNew": "wrk-tafel"
}
