### Login
POST {{baseApiPath}}/login?username={{username}}&password={{password}}

> {%
    client.global.set("jwt", response.body["token"]);
%}

### Login fails - user not found
POST {{baseApiPath}}/login?username=wrong&password=wrong

### Login fails - wrong password
POST {{baseApiPath}}/login?username=admin&password=wrong

### Change password
POST {{baseApiPath}}/users/change-password
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "passwordCurrent": "12345",
  "passwordNew": "wrk-tafel"
}
