stages:
  - build
  - test
  - e2e-test
  - package
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

services:
  - docker:20.10.8-dind

cache:
  paths:
    - frontend/node_modules
    - .m2/repository

build-backend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw clean install -DskipTests -f backend/pom.xml
  artifacts:
    paths:
      - backend/target/admin-backend-0.0.0.jar
  when: manual

build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  when: manual

test-backend:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw test -f backend/pom.xml
  when: manual

test-frontend:
  stage: test
  script:
    - cd frontend
    - npm run test
  when: manual

e2e-test:
  stage: e2e-test
  script:
    - cd frontend
    - npm run e2e
  when: manual

package-backend:
  stage: package
  script:
    - echo "test"
  when: manual

package-frontend:
  stage: package
  script:
    - echo "test"
  when: manual

deploy-to-test:
  stage: deploy
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  script:
    - echo "deploy"
  when: manual

deploy-to-production:
  stage: deploy
  environment:
    name: prod
    url: "https://adminneu.tafel1030.at"
  script:
    - echo "deploy"
  when: manual
