workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

stages:
  - build
  - test
  - package
  - e2e-test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: tafel-admin
  paths:
    - frontend/node_modules
    - .m2/repository

build-backend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw clean install -DskipTests -f backend/pom.xml
  artifacts:
    paths:
      - backend/target
    expire_in: 1 week

build-frontend-test:
  stage: build
  image: node:14.17.6-buster-slim
  script:
    - npm install --prefix frontend
    - npm run build-test --prefix frontend
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week

test-backend:
  stage: test
  image: openjdk:11-jdk-slim
  cache: { }
  script:
    - ./mvnw test -f backend/pom.xml
  when: manual

test-frontend:
  stage: test
  image: node:14.17.6-buster-slim
  cache: { }
  script:
    - npm install --prefix frontend
    # - npm run test --prefix frontend
    - echo "TODO headless run"
  when: manual

pkg-backend:
  stage: package
  # TODO
  #  needs:
  #    - test-backend
  needs:
    - build-backend
  image: docker:dind
  cache: { }
  services:
    - name: docker:20.10.8-dind
      alias: docker
  script:
    - docker build -t tafel/admin-backend:${CI_COMMIT_SHORT_SHA} _build/backend

pkg-frontend-test:
  stage: package
  #  needs:
  #    - test-frontend
  needs:
    - build-frontend-test
  image: docker:dind
  cache: { }
  services:
    - name: docker:20.10.8-dind
      alias: docker
  script:
    - docker build -t tafel/admin-frontend:test-${CI_COMMIT_SHORT_SHA} _build/frontend

deploy-test:
  stage: deploy
  needs:
    - pkg-backend
    - pkg-frontend-test
  cache: { }
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  script:
    - echo "deploy"
  when: manual
