stages:
  - build
  - test
  - e2e-test
  - deploy-test
  - deploy-production

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod 755 gradlew

build-backend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./gradlew :backend:bootBuildImage

build-frontend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./gradlew -w :frontend:npm_run_build :frontend:docker
  when: manual

test-backend:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - ./gradlew -w :backend:test
  when: manual

test-frontend:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - ./gradlew -w :frontend:test
  when: manual

e2e-test:
  stage: e2e-test
  script:
    - echo "e2e-test"
  when: manual

deploy-to-test:
  stage: deploy-test
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  script:
    - echo "deploy"
  when: manual

deploy-to-production:
  stage: deploy-production
  environment:
    name: prod
    url: "https://adminneu.tafel1030.at"
  script:
    - echo "deploy"
  when: manual
