stages:
  - build
  - test
  - e2e-test
  - deploy

build:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"

e2e-test:
  stage: e2e-test
  script:
    - echo "e2e-test"

deploy-test:
  stage: deploy
  script:
    - echo "deploy"
