workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

stages:
  - build
  - test
  - package
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: tafel-admin
  paths:
    - frontend/node_modules
    - .m2/repository

build-backend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw clean install -DskipTests -f backend/pom.xml
  artifacts:
    paths:
      - backend/target
    expire_in: 1 week

build-frontend:
  stage: build
  image: node:14.17.6-buster-slim
  script:
    - npm install --prefix frontend
    - npm run build-test --prefix frontend
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week

test-backend:
  stage: test
  image: openjdk:11-jdk-slim
  cache: { }
  script:
    - ./mvnw test -f backend/pom.xml
  when: manual

test-frontend:
  stage: test
  image: node:14.17.6-buster-slim
  cache: { }
  script:
    - npm install --prefix frontend
    # - npm run test --prefix frontend
    - echo "TODO headless run"
  when: manual

# TODO e2etest

package:
  stage: package
  needs:
    - build-backend
    - build-frontend
  #  needs:
  #    - test-backend
  #    - test-frontend
  image: docker:20.10.10-dind-alpine3.14
  cache: { }
  services:
    - name: docker:20.10.10-dind-alpine3.14
      alias: docker
  script:
    - docker build -t tafel/deploy-base:latest -f _deploy/image/Dockerfile .
    - docker build -t tafel/admin-backend:build-${CI_COMMIT_SHORT_SHA} -f _build/backend/Dockerfile .
    - docker build -t tafel/admin-frontend:build-${CI_COMMIT_SHORT_SHA} -f _build/frontend/Dockerfile .

.deploy:
  stage: deploy
  cache: { }
  image: tafel/deploy-base:latest
  services:
    - name: docker:20.10.10-dind-alpine3.14
      alias: docker
  script:
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "id"
    - echo $ROOT_PWD | ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "sudo id"

deploy-test:
  extends: .deploy
  needs:
    - package
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  variables:
    DEPLOY_SOURCE: test
    DEPLOY_TARGET: /toet/docker/adminneu-test
  when: manual

# add scheduled step / cleanup docker images (*:build-*)