stages:
  - build
  - test
  - e2e-test
  - deploy-test
  - deploy-production

variables:
  DOCKER_HOST: tcp://docker:2376

services:
  - docker:20.10.8-dind

cache:
  key: tafel-admin
  paths:
    - frontend/node_modules

build-backend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw clean install -DskipTests
  when: manual

build-frontend:
  stage: build
  image: openjdk:11-jdk-slim
  script:
    - npm install
    - cd frontend
    - ng build
  artifacts:
    paths:
      - frontend/dist
  when: manual

test-backend:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - ./mvnw test
  when: manual

test-frontend:
  stage: test
  image: openjdk:11-jdk-slim
  script:
    - cd frontend
    - ng test
  when: manual

e2e-test:
  stage: e2e-test
  script:
    - cd frontend
    - ng e2e
  when: manual

deploy-to-test:
  stage: deploy-test
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  script:
    - echo "deploy"
  when: manual

deploy-to-production:
  stage: deploy-production
  environment:
    name: prod
    url: "https://adminneu.tafel1030.at"
  script:
    - echo "deploy"
  when: manual
