stages:
  - build
  - test
  - e2e-test
  - deploy-test
  - deploy-production

build-frontend:
  stage: build
  script:
    - sleep 20
    - echo "build frontend"

build-backend:
  stage: build
  script:
    - sleep 20
    - echo "build backend"

test-frontend:
  stage: test
  script:
    - sleep 20
    - echo "test"

test-backend:
  stage: test
  script:
    - sleep 20
    - echo "test"

e2e-test:
  stage: e2e-test
  script:
    - echo "e2e-test"

deploy-to-test:
  stage: deploy-test
  environment:
    name: test
    url: "https://adminneu-test.tafel1030.at"
  script:
    - echo "deploy"

deploy-to-production:
  stage: deploy-production
  environment:
    name: prod
    url: "https://adminneu.tafel1030.at"
  script:
    - echo "deploy"
  when: manual
