stages:
  - build
  - test
  - e2e-test
  - deploy-test
  - deploy-production

build:
  stage: build
  script:
    - echo "build"

test:
  stage: test
  script:
    - echo "test"

e2e-test:
  stage: e2e-test
  script:
    - echo "e2e-test"

deploy-to-test:
  stage: deploy-test
  environment:
    - test
  script:
    - echo "deploy"

deploy-to-production:
  stage: deploy-production
  environment:
    - prod
  script:
    - echo "deploy"
  when: manual
