version: "3.6"

services:
  database:
    image: "postgres:14.0-alpine3.14"
    container_name: tafeladmin-postgres
    hostname: tafeladmin-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - tafeladmin_net

  pgadmin:
    image: "dpage/pgadmin4:6.1"
    container_name: tafeladmin-pgadmin
    hostname: tafeladmin-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: defaultmail@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - tafeladmin_net

  ui-remote:
    image: ikt01toet1030/wrk-tafel-admin:latest
    restart: unless-stopped
    container_name: tafeladmin-ui
    hostname: tafeladmin-ui
    ports:
      - "8081:8080"
    volumes:
      - ../backend/src/main/resources/application-local.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    networks:
      - tafeladmin_net

#  ui-local-build:
#    build:
#      context: .
#    image: local-build/wrk-tafel-admin:latest
#    restart: unless-stopped
#    container_name: tafeladmin-ui
#    hostname: tafeladmin-ui
#    ports:
#      - "8082:8080"
#    volumes:
#      - ../backend/src/main/resources/application-local.yml:/config/application.yml
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
#    networks:
#      - tafeladmin_net

volumes:
  database-data:
  pgadmin-data:

networks:
  tafeladmin_net:
    name: tafeladmin_net
