### List customers
GET {{baseApiPath}}/customers?pageIndex=3

### Search for customers (only firstname)
GET {{baseApiPath}}/customers?firstname=x

### Search for customers (only lastname)
GET {{baseApiPath}}/customers?lastname=x

### Search for customers (firstname and lastname)
GET {{baseApiPath}}/customers?firstname=x&lastname=x

### Validate customer
POST {{baseApiPath}}/customers/validate
Content-Type: application/json

{
  "firstname": "Eva",
  "lastname": "Musterfrau",
  "birthDate": "1990-01-01",
  "gender": "FEMALE",
  "country": {
    "id": 2,
    "code": "EG",
    "name": "Ägypten"
  },
  "address": {
    "street": "Erdberg",
    "houseNumber": "2",
    "stairway": "1",
    "door": "20",
    "postalCode": 1010,
    "city": "Wien"
  },
  "telephoneNumber": "00436645678953",
  "email": "eva.musterfrau@wrk.at",
  "employer": "Rotes Kreuz Wien",
  "income": 456.00,
  "incomeDue": "2999-12-31",
  "validUntil": "2999-12-31",
  "additionalPersons": [
    {
      "id": 1,
      "firstname": "Child 1",
      "lastname": "Musterfrau",
      "birthDate": "2000-01-01",
      "gender": "MALE",
      "income": 500,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    },
    {
      "id": 2,
      "firstname": "Child 2",
      "lastname": "Musterfrau",
      "birthDate": "2020-01-01",
      "income": 0,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    },
    {
      "id": 3,
      "firstname": "Child 3",
      "lastname": "Musterfrau",
      "birthDate": "2020-01-01",
      "income": null,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    }
  ]
}

### Create customer
POST {{baseApiPath}}/customers
Content-Type: application/json

{
  "firstname": "Test",
  "lastname": "Example",
  "birthDate": "1990-01-01",
  "gender": "FEMALE",
  "country": {
    "id": 2,
    "code": "AT",
    "name": "Österreich"
  },
  "address": {
    "street": "Erdberg",
    "houseNumber": "2",
    "stairway": "1",
    "door": "20",
    "postalCode": 1010,
    "city": "Wien"
  },
  "telephoneNumber": "00436645678953",
  "email": "eva.musterfrau@wrk.at",
  "employer": "Rotes Kreuz Wien",
  "income": 456.00,
  "incomeDue": "2999-12-31",
  "validUntil": "2999-12-31",
  "additionalPersons": [
    {
      "id": 1,
      "firstname": "Child 1",
      "lastname": "Musterfrau",
      "birthDate": "2000-01-01",
      "employer": "Stadt Wien",
      "income": 500,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    },
    {
      "firstname": "Child 2",
      "lastname": "Musterfrau",
      "birthDate": "2020-01-01",
      "income": 0,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    },
    {
      "firstname": "Child 3",
      "lastname": "Musterfrau",
      "birthDate": "2020-01-01",
      "income": null,
      "country": {
        "id": 2,
        "code": "EG",
        "name": "Ägypten"
      }
    }
  ]
}

### Get customer 100
GET {{baseApiPath}}/customers/100
Content-Type: application/json

### Delete customer 100
DELETE {{baseApiPath}}/customers/100
Content-Type: application/json

### Get masterdata pdf
GET {{baseApiPath}}/customers/100/generate-pdf?type=MASTERDATA
Content-Type: application/json

### Get idcard pdf
GET {{baseApiPath}}/customers/100/generate-pdf?type=IDCARD
Content-Type: application/json

### Get combined pdf
GET {{baseApiPath}}/customers/100/generate-pdf?type=COMBINED
Content-Type: application/json

### Get duplicates
GET {{baseApiPath}}/customers/duplicates
Content-Type: application/json
