### Get distributions
GET {{baseApiPath}}/distributions

### Create a new distribution
POST {{baseApiPath}}/distributions/new

### Close currently open distribution
POST {{baseApiPath}}/distributions/close

### Listen for distribution changes
GET {{baseApiPath}}/sse/distributions
Accept: text/event-stream

### Assign household to distribution
POST {{baseApiPath}}/distributions/households
Content-Type: application/json

{
  "householdId": 100,
  "ticketNumber": 100
}

### Save statistic data to distribution
POST {{baseApiPath}}/distributions/statistics
Content-Type: application/json

{
  "employeeCount": 100,
  "selectedShelterIds": [1, 2, 3]
}

### Save notes for distribution
POST {{baseApiPath}}/distributions/notes
Content-Type: application/json

{
  "notes": "Everything went well!"
}

### Get customer list (pdf)
GET {{baseApiPath}}/distributions/households/generate-pdf

### Send mails for distribution
POST {{baseApiPath}}/distributions/100/send-mails
