### Show text on ticket screen
POST {{baseApiPath}}/distributions/ticket-screen/show-text
Content-Type: application/json

{
  "text": "Hello world",
  "value": "123"
}

### Show current ticket on ticket screen
POST {{baseApiPath}}/distributions/ticket-screen/show-current

### Show previous ticket on ticket screen
POST {{baseApiPath}}/distributions/ticket-screen/show-previous

### Show next ticket on ticket screen
POST {{baseApiPath}}/distributions/ticket-screen/show-next
Content-Type: application/json

{
  "costContributionPaid": true
}

### Listen for ticket screen changes
GET {{baseApiPath}}/sse/distributions/ticket-screen/current
Accept: text/event-stream
