### Get collected food for route X
GET {{baseApiPath}}/food-collections/route/1

### Save route data
POST {{baseApiPath}}/food-collections/route/1
Content-Type: application/json

{
  "routeId": 1,
  "carLicensePlate": "W-12345",
  "driverId": 100,
  "coDriverId": 100,
  "kmStart": 100,
  "kmEnd": 200
}

### Save food items
POST {{baseApiPath}}/food-collections/route/1/items
Content-Type: application/json

{
  "items": [
    {
      "categoryId": 1,
      "shopId": 20,
      "amount": 1
    },
    {
      "categoryId": 1,
      "shopId": 21,
      "amount": 2
    }
  ]
}

### Save food items per shop
POST {{baseApiPath}}/food-collections/route/1/shop/1/items
Content-Type: application/json

{
  "items": [
    {
      "categoryId": 1,
      "amount": 1
    },
    {
      "categoryId": 2,
      "amount": 2
    }
  ]
}

### Get food items per shop
GET {{baseApiPath}}/food-collections/route/1/shop/1/items

### Patch a single food item
PATCH {{baseApiPath}}/food-collections/route/1/items
Content-Type: application/json

{
  "categoryId": 1,
  "shopId": 20,
  "amount": 1
}
