### Fetch all scanner ids
GET {{baseApiPath}}/scanners

### Register new scanner
POST {{baseApiPath}}/scanners/register

### Re-Register existing scanner
POST {{baseApiPath}}/scanners/register?scannerId=123

### Fetch results from scanner with id 1
GET {{baseApiPath}}/sse/scanners/1/results
Content-Type: text/event-stream

### Send new result from scanner with id 1
POST {{baseApiPath}}/scanners/1/results?scanResult=815
