### Get mail-recipient settings
GET {{baseApiPath}}/settings/mail-recipients

### Update mail-recipient settings
PUT {{baseApiPath}}/settings/mail-recipients
Content-Type: application/json

{
  "settings": [
    {
      "mailType": {
        "name": "DAILY_REPORT",
        "label": "Tagesreport"
      },
      "recipients": {
        "to": [
          "dailyreport-to1@domain.com",
          "dailyreport-to2@domain.com"
        ],
        "cc": [
          "dailyreport-cc@domain.com"
        ],
        "bcc": [
          "dailyreport-bcc@domain.com"
        ]
      }
    },
    {
      "mailType": {
        "name": "STATISTICS",
        "label": "Statistiken"
      },
      "recipients": {
        "to": [
          "statistics-to@domain.com"
        ]
      }
    },
    {
      "mailType": {
        "name": "RETURN_BOXES",
        "label": "Retourkisten"
      },
      "recipients": {
        "to": [
          "returnboxes-to@domain.com"
        ]
      }
    }
  ]
}

### Get static values
GET {{baseApiPath}}/settings/static-values

### Update static value 1
PUT {{baseApiPath}}/settings/static-values/1
Content-Type: application/json

{
  "id": 1,
  "type": "INCOME_LIMIT",
  "validFrom": "2026-01-01",
  "validTo": "2999-12-31",
  "amount": 150
}

### Get login attempts
GET {{baseApiPath}}/settings/login-attempts

### Delete login attempt 1
DELETE {{baseApiPath}}/settings/login-attempts/1
