### Fetch all shops
GET {{baseApiPath}}/shops

### Create a shop
POST {{baseApiPath}}/shops
Content-Type: application/json

{
  "number": 5000,
  "name": "Neue Filiale",
  "addressStreet": "Teststraße 1",
  "addressPostalCode": 1100,
  "addressCity": "Wien",
  "foodUnit": "BOX",
  "phone": "01 234 56 78",
  "contactPerson": "Fr. Musterfrau",
  "note": "Notiz zur Filiale",
  "enabled": true
}

### Update a shop
PUT {{baseApiPath}}/shops/1
Content-Type: application/json

{
  "id": 1,
  "number": 100,
  "name": "Billa",
  "addressStreet": "Bloch-Bauer-Promenade 1",
  "addressPostalCode": 1100,
  "addressCity": "Wien",
  "foodUnit": "BOX",
  "phone": "01 23 45 67 89",
  "contactPerson": "Fr. Musterfrau",
  "note": null,
  "enabled": true
}
