### Login
POST {{baseApiPath}}/login
Authorization: Basic {{encodedCredentials}}

### Login fails - user not found
POST {{baseApiPath}}/login
Authorization: Basic d3Jvbmc6d3Jvbmc=

### Login fails - wrong password
POST {{baseApiPath}}/login
Authorization: Basic YWRtaW46d3Jvbmc=

### Change password
POST {{baseApiPath}}/users/change-password
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "passwordCurrent": "12345",
  "passwordNew": "wrk-tafel"
}

### Logout
POST {{baseApiPath}}/users/logout

### Search for users (personnelNumber)
GET {{baseApiPath}}/users?personnelnumber=x

### Search for users (all other parameters)
GET {{baseApiPath}}/users?firstname=x&lastname=x&username=x&enabled=true

### Search for users (enabled)
GET {{baseApiPath}}/users?enabled=true

### Get user 300
GET {{baseApiPath}}/users/300
Content-Type: application/json

### Get user admin by personnel-number
GET {{baseApiPath}}/users/personnel-number/admin-persnr
Content-Type: application/json

### Update user
POST {{baseApiPath}}/users/300
Content-Type: application/json

{
  "id": 300,
  "personnelNumber": "0300",
  "username": "admin",
  "firstname": "AD",
  "lastname": "min",
  "enabled": false,
  "password": "12345",
  "passwordRepeat": "12345",
  "passwordChangeRequired": true,
  "permissions": []
}

### Generate a random password
GET {{baseApiPath}}/users/generate-password
Content-Type: application/json

### Get all available permissions
GET {{baseApiPath}}/users/permissions
Content-Type: application/json
