server:
  servlet:
    session:
      cookie:
        path: / # TODO configurable for contextpaths of e.g. nginx

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db-migration
    group: true
    ignoreMissingMigrations: true

security:
  jwtToken:
    secret:
      algorithm: HmacSHA512
    expirationTimeInSeconds: 36000 # 10 hours

tafeladmin:
  baseUrl: https://localhost:4200:/path # in case of reverse proxy with relative path
