logging:
  level:
    root: INFO
    org.apache: INFO
    org.springframework.security: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tafeladmin
    username: tafeladmin
    password: admin
  mail:
    host: localhost
    port: 1025
    username: mailhog
    password: mailhog

security:
  jwtToken:
    issuer: http://localhost
    audience: wrk-tafel
    secret.value: 8a58255b49728fe758502948917ae98709b7cc502e4c7a0d3bc9d183b5be24378a58255b49728fe758502948917ae98709b7cc502e4c7a0d3bc9d183b5be24378a58255b49728fe758502948917ae98709b7cc502e4c7a0d3bc9d183b5be24378a58255b49728fe7585012
    expirationTimeInSeconds: 604800 # 1 week for local development

tafeladmin:
  mail:
    from: "dummy@localhost"
    subjectPrefix: "LOCAL-DEV-"
    dailyReport:
      to:
        - "to1@localhost"
        - "to2@localhost"
      cc:
        - "cc1@localhost"
        - "cc2@localhost"
      bcc:
        - "bcc1@localhost"
        - "bcc2@localhost"
    statistic:
      to:
        - "to1@localhost"
        - "to2@localhost"
    summaryMail:
      to:
        - "to1@localhost"
        - "to2@localhost"
