management:
  server:
    port: 8081
  endpoints.web.exposure.include: caches

server:
  port: 8080
  servlet.session.cookie.path: ${tafeladmin.server.relativeBaseUrl}
  tomcat.accesslog:
    enabled: true
    directory: ${user.dir}/logs
    buffered: false
    prefix: access
    suffix: .log
    rotate: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db-migration
    group: true
    ignoreMissingMigrations: true

security:
  jwtToken:
    secret.algorithm: HmacSHA512
    expirationTimeInSeconds: 36000 # 10 hours

tafeladmin:
  server:
    relativeBaseUrl: /
