logging:
  level:
    root: INFO
    org.apache: WARN
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN

management:
  server:
    port: 8081
  endpoints.web.exposure.include: caches,env,prometheus

server:
  port: 8080
  servlet:
    session.cookie.path: ${tafeladmin.server.relativeBaseUrl}
  error:
    include-message: always
    include-stacktrace: always
  tomcat:
    accesslog:
      enabled: true
      directory: ${user.dir}/logs
      buffered: false
      prefix: access
      suffix: .log
      rotate: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
  flyway:
    locations: classpath:/db-migration
    group: true
    ignore-migration-patterns: "*:missing"
    baseline-on-migrate: true
    clean-disabled: false
  mail:
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  jpa:
    properties:
      hibernate:
        id:
          db_structure_naming_strategy: single # TODO migrate to new default strategy (sequence per table)
    open-in-view: false
  thymeleaf:
    prefix: classpath:/mail-templates/
  mvc:
    async:
      request-timeout: 3600000 # 1 hour

security:
  jwtToken:
    secret.algorithm: HMACSHA256
    expirationTimeInSeconds: 36000 # 10 hours
    expirationTimePwdChangeInSeconds: 300 # 5 minutes

tafeladmin:
  server:
    relativeBaseUrl: /
