logging:
  level:
    root: INFO
    org.apache: WARN

management:
  server:
    port: 8081
  endpoints.web.exposure.include: caches,env,prometheus

server:
  port: 8080
  servlet.session.cookie.path: ${tafeladmin.server.relativeBaseUrl}
  tomcat.accesslog:
    enabled: true
    directory: ${user.dir}/logs
    buffered: false
    prefix: access
    suffix: .log
    rotate: false

spring:
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db-migration
    group: true
    ignore-migration-patterns: "*:missing"

security:
  jwtToken:
    secret.algorithm: HmacSHA512
    expirationTimeInSeconds: 36000 # 10 hours

tafeladmin:
  server:
    relativeBaseUrl: /
