logging:
  level:
    root: INFO
    org.apache: WARN
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN

management:
  server:
    port: 8081
  endpoints.web.exposure.include: caches,env,prometheus

server:
  port: 8080
  servlet.session.cookie.path: ${tafeladmin.server.relativeBaseUrl}
  tomcat.accesslog:
    enabled: true
    directory: ${user.dir}/logs
    buffered: false
    prefix: access
    suffix: .log
    rotate: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:/db-migration
    group: true
    ignore-migration-patterns: "*:missing"
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    properties:
      hibernate:
        id:
          db_structure_naming_strategy: single # TODO migrate to new default strategy (sequence per table)

security:
  jwtToken:
    secret.algorithm: HmacSHA512
    expirationTimeInSeconds: 36000 # 10 hours
    expirationTimePwdChangeInSeconds: 300 # 5 minutes

tafeladmin:
  server:
    relativeBaseUrl: /
