name: Push on main branch

concurrency: release

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ] # TODO switch to separate release branch later on

jobs:
  build-and-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_test.yml@main
  analysis:
    uses: wrk-tafel/admin/.github/workflows/subflow_analysis.yml@main
  e2e-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_e2e_test.yml@main
    needs: build-and-test
  docker-image:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_image.yml@main
    needs: e2e-test
  dockerhub:
    uses: wrk-tafel/admin/.github/workflows/subflow_publish_image.yml@main
    needs: docker-image
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    uses: wrk-tafel/admin/.github/workflows/subflow_deploy.yml@main
    needs: dockerhub
    secrets:
      sshKey: ${{ secrets.SSH_DEPLOY_KEY }}
      sshKnownHosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      sshDeployCommand: ${{ secrets.SSH_DEPLOY_COMMAND }}
