name: Main Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SONAR_QUALITYGATE_WAIT: false

jobs:
  build:
    uses: ./.github/workflows/subflow_build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-test:
    uses: ./.github/workflows/subflow_e2e_test.yml
    needs: build
