name: Build and publish main branch

on:
  push:
    branches: [ 'main' ] # switch to seperate release branch later on

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'adopt'
  KTLINT_VERSION: '0.43.2'
  IMAGE_NAME: rktafel/admin:latest

jobs:
  build-and-test:
    uses: wrk-tafel/admin/.github/workflows/flows/build_test.yml
    with:
      java-version: ${{ env.JAVA_VERSION }}
      java-distribution: ${{ env.JAVA_DISTRIBUTION }}
      ktlint-version: ${{ env.KTLINT_VERSION }}
  publish-image:
    uses: wrk-tafel/admin/.github/workflows/flows/publish_image.yml
    with:
      secrets:
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerimage-name: ${{ env.IMAGE_NAME }}
