name: Build and publish main branch

on:
  push:
    branches: [ 'main' ] # switch to seperate release branch later on

jobs:
  build-and-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_test.yml@main
    with:
      java-version: '17'
      java-distribution: 'adopt'
      ktlint-version: '0.43.2'
  publish-image:
    uses: wrk-tafel/admin/.github/workflows/subflow_publish_image.yml@main
    with:
      secrets:
        dockerimage-name: 'rktafel/admin:latest'
