name: Pull Request

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/subflow_build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  analysis-lint:
    uses: ./.github/workflows/subflow_analysis_lint.yml
  e2e-test:
    uses: ./.github/workflows/subflow_e2e_test.yml
    needs: build
