name: Pull Request

on:
  pull_request:

jobs:
  build:
    uses: wrk-tafel/admin/.github/workflows/subflow_build.yml@main
  test:
    uses: wrk-tafel/admin/.github/workflows/subflow_test.yml@main
    needs: build
  analysis-lint:
    uses: wrk-tafel/admin/.github/workflows/subflow_analysis_lint.yml@main
  e2e-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_e2e_test.yml@main
    needs: build
