name: Pull Request

on:
  pull_request:

jobs:
  build-and-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_test.yml@main
  analysis:
    uses: wrk-tafel/admin/.github/workflows/subflow_analysis.yml@main

# TEST