name: Pull Request

on:
  pull_request:

jobs:
  build-and-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_test.yml@main
  analysis:
    uses: wrk-tafel/admin/.github/workflows/subflow_analysis.yml@main
  docker-image:
    uses: wrk-tafel/admin/.github/workflows/subflow_build_image.yml@main
    needs: build-and-test
  e2e-test:
    uses: wrk-tafel/admin/.github/workflows/subflow_e2e_test.yml@main
    needs: docker-image
