name: Pull Request

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/subflow_build.yml
  analysis-lint:
    uses: ./.github/workflows/subflow_analysis_lint.yml
  test-backend:
    uses: ./.github/workflows/subflow_test-backend.yml
    needs: build
  test-frontend:
    uses: ./.github/workflows/subflow_test-frontend.yml
    needs: build
  e2e-test:
    uses: ./.github/workflows/subflow_e2e_test.yml
    needs: build
