name: Publish docker image

env:
  IMAGE_NAME: 'rktafel/admin:latest'

on:
  workflow_call:
    secrets:
      dockerHubUsername:
        required: true
      dockerHubToken:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: admin-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/admin-image.tar
          docker image ls -a
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerHubUsername }}
          password: ${{ secrets.dockerHubToken }}
      - name: Push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
