name: Build and Analyze

env:
  JAVA_VERSION: '25'
  JAVA_DISTRIBUTION: 'corretto'

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # allows SonarCloud to decorate PRs with analysis results
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: 'frontend/src/main/webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/src/main/webapp/package-lock.json'
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0f4528296b4bc09e8ae0fc7be30185a4ab435545 # v6.0.0
      - name: Build and Test
        run: ./gradlew build
      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dsonar.projectKey=wrk-tafel-admin -Dsonar.organization=wrk-tafel -Dsonar.token=$SONAR_TOKEN
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: always()
        with:
          name: backend-custom-test-results
          path: ./backend/build/custom-test-results/
          if-no-files-found: ignore
          retention-days: 14
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: admin-jarfile
          path: ./backend/build/libs/admin-backend.jar
          if-no-files-found: error
          retention-days: 1
