name: Build and Test

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'adopt'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: 'frontend/src/main/webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/src/main/webapp/package-lock.json'
      - name: Run tests
        run: ./mvnw -pl frontend --fail-at-end test verify
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: frontend-codecoverage-report
          path: ./frontend/src/main/webapp/coverage/
          if-no-files-found: error
          retention-days: 14
