name: Build and Test

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'adopt'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'
      - name: Execute maven build
        run: ./mvnw clean install -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: admin-jarfile
          path: ./backend/target/admin-backend.jar
          if-no-files-found: error
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'
      - uses: actions/setup-node@v3.1.1
        with:
          node-version-file: 'frontend/src/main/webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/src/main/webapp/package-lock.json'
      - name: Run tests
        run: ./mvnw --fail-at-end test verify
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backend-codecoverage-reports
          path: |
                ./backend/**/target/site/jacoco/
                ./backend/modules/**/target/site/jacoco/
          if-no-files-found: error
          retention-days: 14
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: frontend-codecoverage-report
          path: ./frontend/src/main/webapp/coverage/
          if-no-files-found: error
          retention-days: 14
