name: Deploy to server

on:
  workflow_call:
    secrets:
      sshKey:
        required: true
      sshKnownHosts:
        required: true
      sshDeployCommand:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.sshKey }}
          SSH_KNOWN_HOSTS: ${{ secrets.sshKnownHosts }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Deploy to server
        run: ${{ secrets.sshDeployCommand }}
