name: Publish docker image

env:
  IMAGE_NAME: 'rktafel/admin:latest'

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: admin-jarfile
          path: ./artifact
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: _build/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}

# TODO e2e-test, tslint
