name: Publish docker image

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
    secrets:
      dockerHubUsername:
        required: true
      dockerHubToken:
        required: true

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: admin-jarfile
          path: ./artifact
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerHubUsername }}
          password: ${{ secrets.dockerHubToken }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: _build/Dockerfile
          push: true
          tags: ${{ inputs.imageName }}

# TODO e2e-test, tslint
