name: Build and Analyze

env:
  JAVA_VERSION: '26'
  JAVA_DISTRIBUTION: 'corretto'

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # allows SonarCloud to decorate PRs with analysis results
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # SonarCloud needs full history for blame and branch comparison
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: 'frontend/src/main/webapp/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/src/main/webapp/package-lock.json'
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-provider: basic
      - name: Build and Test
        run: ./gradlew build
      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -Dsonar.projectKey=wrk-tafel-admin -Dsonar.organization=wrk-tafel -Dsonar.token=$SONAR_TOKEN
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: backend-custom-test-results
          path: ./backend/build/custom-test-results/
          if-no-files-found: ignore
          retention-days: 14
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: admin-jarfile
          path: ./backend/build/libs/admin-backend.jar
          if-no-files-found: error
          retention-days: 1
