name: Build and Test

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'adopt'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.10.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'
      - name: Run tests
        run: ./mvnw -pl backend --fail-at-end test verify
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backend-codecoverage-reports
          path: ./backend/target/site/jacoco/
          if-no-files-found: error
          retention-days: 14
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backend-custom-test-results
          path: ./backend/target/custom-test-results/
          if-no-files-found: ignore
          retention-days: 14
